//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen01.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PV_Examen01Entities : DbContext
    {
        public PV_Examen01Entities()
            : base("name=PV_Examen01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<spConsultarTodosLosProductos_Result> spConsultarTodosLosProductos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarTodosLosProductos_Result>("spConsultarTodosLosProductos");
        }
    
        public virtual int spCrearProducto(string nombre, Nullable<int> cantidad, Nullable<decimal> precioUnitario, Nullable<System.DateTime> fechaRegistro)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var precioUnitarioParameter = precioUnitario.HasValue ?
                new ObjectParameter("precioUnitario", precioUnitario) :
                new ObjectParameter("precioUnitario", typeof(decimal));
    
            var fechaRegistroParameter = fechaRegistro.HasValue ?
                new ObjectParameter("fechaRegistro", fechaRegistro) :
                new ObjectParameter("fechaRegistro", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCrearProducto", nombreParameter, cantidadParameter, precioUnitarioParameter, fechaRegistroParameter);
        }
    }
}
